kind: pipeline
name: default

steps:
  - name: testing
    image: golang:1.12
    pull: true
    commands:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic ./... ./pgx-pgcall/... ./gin-pgcall/...
      - go vet ./... ./pgx-pgcall/... ./gin-pgcall/...

  - name: create-db
    image: postgres:11.2-alpine
    commands:
    - until pg_isready -q -U postgres -h database ; do sleep 1 ; echo -n "." ; done
    - psql -U postgres --single-transaction -d test -h database -f testdata/schema.sql
    environment:
      WORKDIR: /drone/src/testdata

  - name: testing-db
    image: golang:1.12
    pull: true
    commands:
      - sleep 15
      - go test -v -race -coverprofile=coverage.out -covermode=atomic -tags="db nocommon" ./... ./pgx-pgcall/... ./gin-pgcall/...
      - curl -s https://codecov.io/bash | bash
    environment:
      CODECOV_TOKEN:
        from_secret: my-codecov-token
      DB_SCHEMA:   rpc,public
      DB_LOGLEVEL: debug
      PGHOST:      database
      PGDATABASE:  test
      PGUSER:      postgres
      PGAPPNAME:   pgcall

services:
  - name: database
    image: postgres:11.2-alpine
    ports:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
