kind: pipeline
name: default

steps:
  - name: wait-for-db
    image: postgres:11.4-alpine
    commands:
    - until pg_isready -q -U postgres -h database ; do sleep 1 ; echo -n "." ; done
  - name: submodules
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update --recursive --remote
  - name: testing-db
    image: golang:1.13
    pull: true
    commands:
      - go test -v -race -coverprofile=coverage.out -covermode=atomic -tags=db ./...
      - curl -s https://codecov.io/bash | bash
    environment:
      CODECOV_TOKEN:
        from_secret: my-codecov-token
      PGHOST:      database
      PGDATABASE:  test
      PGUSER:      postgres
      PGAPPNAME:   procapi
      TZ:          Europe/Berlin

services:
  - name: database
    image: postgres:11.4-alpine
    ports:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: test
